# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    steps:
    - task: Maven@1
      displayName: Maven
      inputs:
        mavenPomFile: 'webgoat/pom.xml'
        mavenOptions: '-Xmx3072m -Dmaven.test.skip=true' 
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        goals: 'package'

- stage: scan
  displayName: Scan stage
  jobs:
  - job: Scan
    displayName: Scan Job
    steps:
    - task: NexusIqPipelineTask@1
      inputs:
        nexusIqService: 'iq'
        applicationId: 'webgoat'
